name: Desolee
title: Desolee Cards
description: Choose a difficulty:\nEasy, Medium, Hard, or Expert
# theme: minima
remote_theme: pages-themes/merlot@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
